### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] Add Lidar

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#14]
p. 8  more and more spatial data is available as Lidar point clouds or other formats that don't follow the traditional vector/raster approach. 

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/d6afecfc-ac6e-4dfb-9b47-cb6a08843ef7)

For example, https://hcommons.social/@aejolene/110532023569034904 "Any [#archaeology](https://hcommons.social/tags/archaeology) and/or [#digitalarchives](https://hcommons.social/tags/digitalarchives) folks out there with recommendations on curating Ground Penetrating Radar datasets (DZT, DZX)? Challenges: they are v big & proprietary, we don't even have the software to read them in native format." 

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/bee0a288-37ca-4eb3-8410-945aed60fb15)

**Comment by anitagraser** [comment]
p. 61 This is the first and last time point clouds are mentioned. Are there plans to explicitly address them into future versions of this guideline? 

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/7c61f343-5dba-4994-bc92-a67b91751f72)

**Comment by GregorZavrsnik** [comment]
Additional text was added to the Scope chapter in order to acknowladge newer standards:
"Geospatial domain is developing and many new formats are being used from LIDAR and point clouds to live-streamed data and distributed cloud-based formats. The CITS Geospatial specification is written in a very generic manner, so most of the proposed rules are also applicable to other data types. More examples of standards for newer formats will be added in the future. "
