### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] GEO_35 Rationale - GIS Documentation 

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#35]
p. 62 For general-purpose GIS systems, such as ArcGIS or QGIS, would it be sufficient to refer to the used version? 

This sounds like out-of-scope to me. "This guideline is not describing the usage of CITS Geospatial for GIS and Web services."

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/8f6dfd35-a729-46ce-887e-7da4f8103cbe)

**Comment by GregorZavrsnik** [comment]
As described in the [Issue #20](https://github.com/DILCISBoard/CITS-Geospatial/issues/20), the aim of Archiving is also preserving a broader historical context of the time when the records were used. As this specification is aimed at different audience, this content is optional and can be left out if it doesn't apply to a certain use case. However we describe it, so that there is a possibility to preserve the content required by historical archives.
