### ISSUE TITLE
[Guideline_CITS_Geospatial_v_1_0.pdf] Potential legacy comment

### ISSUE THREAD

**Issue by anitagraser** [DILCISBoard/CITS-Geospatial#37]
p. 85 Is this a left-over comment that should be removed?

![image](https://github.com/DILCISBoard/CITS-Geospatial/assets/590385/aad97346-795c-432a-9a26-407c4d677872)

**Comment by GregorZavrsnik** [comment]
Actually this comment is repeated multiple times, since in the creation of this document we compared the INSPIRE metadata to the ISO 19115-1:2014 standard as well. The INSPIRE metadata guideline was written before ISO 19115-1:2014 was created, so some elements, that were originally in ISO 19115:2003, were not identified in the new version of the standard. And this is the meaning of the sentence.
